package(
    default_testonly = True,
    default_visibility = ["//visibility:private"],
)

licenses(["notice"])

cc_library(
    name = "base_types",
    hdrs = [
        "base_types.h",
    ],
    visibility = ["//visibility:public"],
)
